sonar.projectKey=TestToDo
sonar.projectName=TestToDo
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqp_439e6be0dc45b034bf500e7b254955bfc1ce05c5